In [42]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import os

warnings.filterwarnings('ignore')

In [43]:
BERAU_DATA_PATH = "../datasets/raw/bureau.csv"
IMAGES_PATH = "../images/"
OUTPUT_PATH = "../datasets/preprocess/"

In [44]:
bureau  = pd.read_csv(BERAU_DATA_PATH)

display(bureau .head())
print("\n")
print(bureau.info())

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1716428 entries, 0 to 1716427
Data columns (total 17 columns):
 #   Column                  Dtype
---  ------                  -----
 0   SK_ID_CURR              int64
 1   SK_ID_BUREAU            int64
 2   CREDIT_ACTIVE           object
 3   CREDIT_CURRENCY         object
 4   DAYS_CREDIT             int64
 5   CREDIT_DAY_OVERDUE      int64
 6   DAYS_CREDIT_ENDDATE     float64
 7   DAYS_ENDDATE_FACT       float64
 8   AMT_CREDIT_MAX_OVERDUE  float64
 9   CNT_CREDIT_PROLONG      int64
 10  AMT_CREDIT_SUM          float64
 11  AMT_CREDIT_SUM_DEBT     float64
 12  AMT_CREDIT_SUM_LIMIT    float64
 13  AMT_CREDIT_SUM_OVERDUE  float64
 14  CREDIT_TYPE             object
 15  DAYS_CREDIT_UPDATE      int64
 16  AMT_ANNUITY             float64
dtypes: float64(8), int64(6), object(3)
memory usage: 222.6+ MB
None

In [45]:
bureau .describe()

,SK_ID_CURR,SK_ID_BUREAU,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
count,1.716428e+06,1.716428e+06,1.716428e+06,1.716428e+06,1.610875e+06,1.082775e+06,5.919400e+05,1.716428e+06,1.716415e+06,1.458759e+06,1.124648e+06,1.716428e+06,1.716428e+06,4.896370e+05
mean,2.782149e+05,5.924434e+06,-1.142108e+03,8.181666e-01,5.105174e+02,-1.017437e+03,3.825418e+03,6.410406e-03,3.549946e+05,1.370851e+05,6.229515e+03,3.791276e+01,-5.937483e+02,1.571276e+04
std,1.029386e+05,5.322657e+05,7.951649e+02,3.654443e+01,4.994220e+03,7.140106e+02,2.060316e+05,9.622391e-02,1.149811e+06,6.774011e+05,4.503203e+04,5.937650e+03,7.207473e+02,3.258269e+05
min,1.000010e+05,5.000000e+06,-2.922000e+03,0.000000e+00,-4.206000e+04,-4.202300e+04,0.000000e+00,0.000000e+00,0.000000e+00,-4.705600e+06,-5.864061e+05,0.000000e+00,-4.194700e+04,0.000000e+00
25%,1.888668e+05,5.463954e+06,-1.666000e+03,0.000000e+00,-1.138000e+03,-1.489000e+03,0.000000e+00,0.000000e+00,5.130000e+04,0.000000e+00,0.000000e+00,0.000000e+00,-9.080000e+02,0.000000e+00
50%,2.780550e+05,5.926304e+06,-9.870000e+02,0.000000e+00,-3.300000e+02,-8.970000e+02,0.000000e+00,0.000000e+00,1.255185e+05,0.000000e+00,0.000000e+00,0.000000e+00,-3.950000e+02,0.000000e+00
75%,3.674260e+05,6.385681e+06,-4.740000e+02,0.000000e+00,4.740000e+02,-4.250000e+02,0.000000e+00,0.000000e+00,3.150000e+05,4.015350e+04,0.000000e+00,0.000000e+00,-3.300000e+01,1.350000e+04
max,4.562550e+05,6.843457e+06,0.000000e+00,2.792000e+03,3.119900e+04,0.000000e+00,1.159872e+08,9.000000e+00,5.850000e+08,1.701000e+08,4.705600e+06,3.756681e+06,3.720000e+02,1.184534e+08

In [46]:
(bureau.isna().sum() * 100 / len(bureau ))

SK_ID_CURR                 0.000000
SK_ID_BUREAU               0.000000
CREDIT_ACTIVE              0.000000
CREDIT_CURRENCY            0.000000
DAYS_CREDIT                0.000000
CREDIT_DAY_OVERDUE         0.000000
DAYS_CREDIT_ENDDATE        6.149573
DAYS_ENDDATE_FACT         36.916958
AMT_CREDIT_MAX_OVERDUE    65.513264
CNT_CREDIT_PROLONG         0.000000
AMT_CREDIT_SUM             0.000757
AMT_CREDIT_SUM_DEBT       15.011932
AMT_CREDIT_SUM_LIMIT      34.477415
AMT_CREDIT_SUM_OVERDUE     0.000000
CREDIT_TYPE                0.000000
DAYS_CREDIT_UPDATE         0.000000
AMT_ANNUITY               71.473490
dtype: float64

In [47]:
i = 1
for col in bureau .columns:
    if bureau [col].dtype == "object":
        print(f"{i}. {col} -> unique values: {bureau [col].nunique()}")
        i += 1

1. CREDIT_ACTIVE -> unique values: 4
2. CREDIT_CURRENCY -> unique values: 4
3. CREDIT_TYPE -> unique values: 15

In [48]:
bureau['DAYS_CREDIT'].describe()

count    1.716428e+06
mean    -1.142108e+03
std      7.951649e+02
min     -2.922000e+03
25%     -1.666000e+03
50%     -9.870000e+02
75%     -4.740000e+02
max      0.000000e+00
Name: DAYS_CREDIT, dtype: float64

In [49]:
bureau.duplicated().sum()

0

In [50]:
bureau['SK_ID_BUREAU'].duplicated().sum()

0

In [51]:
bureau['SK_ID_CURR'].duplicated().sum()

1410617

In [52]:
#Group by client and for each column calculate many staticstics
bureau_agg = bureau.groupby('SK_ID_CURR').agg({
    'SK_ID_BUREAU':'count',
    'DAYS_CREDIT':['mean','max','min'],
    'AMT_CREDIT_SUM': ['mean', 'max', 'sum'],
    'AMT_CREDIT_SUM_DEBT': ['mean', 'sum'],
    'CREDIT_DAY_OVERDUE': ['mean', 'max'],
})

display(bureau_agg.head())

           SK_ID_BUREAU  DAYS_CREDIT            AMT_CREDIT_SUM            \
                  count         mean  max   min           mean       max
SK_ID_CURR
100001                7  -735.000000  -49 -1572  207623.571429  378000.0
100002                8  -874.000000 -103 -1437  108131.945625  450000.0
100003                4 -1400.750000 -606 -2586  254350.125000  810000.0
100004                2  -867.000000 -408 -1326   94518.900000   94537.8
100005                3  -190.666667  -62  -373  219042.000000  568800.0

                        AMT_CREDIT_SUM_DEBT           CREDIT_DAY_OVERDUE
                    sum                mean       sum               mean max
SK_ID_CURR
100001      1453365.000        85240.928571  596686.5                0.0   0
100002       865055.565        49156.200000  245781.0                0.0   0
100003      1017400.500            0.000000       0.0                0.0   0
100004       189037.800            0.000000       0.0                0.0   0
100005       657126.000       189469.500000  568408.5                0.0   0

In [53]:
bureau_agg.columns

MultiIndex([(       'SK_ID_BUREAU', 'count'),
            (        'DAYS_CREDIT',  'mean'),
            (        'DAYS_CREDIT',   'max'),
            (        'DAYS_CREDIT',   'min'),
            (     'AMT_CREDIT_SUM',  'mean'),
            (     'AMT_CREDIT_SUM',   'max'),
            (     'AMT_CREDIT_SUM',   'sum'),
            ('AMT_CREDIT_SUM_DEBT',  'mean'),
            ('AMT_CREDIT_SUM_DEBT',   'sum'),
            ( 'CREDIT_DAY_OVERDUE',  'mean'),
            ( 'CREDIT_DAY_OVERDUE',   'max')],
           )

In [54]:
bureau_agg.columns = ['_'.join(col).upper() for col in bureau_agg.columns]

In [55]:
bureau_agg.head()

,SK_ID_BUREAU_COUNT,DAYS_CREDIT_MEAN,DAYS_CREDIT_MAX,DAYS_CREDIT_MIN,AMT_CREDIT_SUM_MEAN,AMT_CREDIT_SUM_MAX,AMT_CREDIT_SUM_SUM,AMT_CREDIT_SUM_DEBT_MEAN,AMT_CREDIT_SUM_DEBT_SUM,CREDIT_DAY_OVERDUE_MEAN,CREDIT_DAY_OVERDUE_MAX
SK_ID_CURR,,,,,,,,,,,
100001,7,-735.000000,-49,-1572,207623.571429,378000.0,1453365.000,85240.928571,596686.5,0.0,0
100002,8,-874.000000,-103,-1437,108131.945625,450000.0,865055.565,49156.200000,245781.0,0.0,0
100003,4,-1400.750000,-606,-2586,254350.125000,810000.0,1017400.500,0.000000,0.0,0.0,0
100004,2,-867.000000,-408,-1326,94518.900000,94537.8,189037.800,0.000000,0.0,0.0,0
100005,3,-190.666667,-62,-373,219042.000000,568800.0,657126.000,189469.500000,568408.5,0.0,0

In [56]:
bureau_agg = bureau_agg.reset_index()

In [57]:
bureau_agg.head()

,SK_ID_CURR,SK_ID_BUREAU_COUNT,DAYS_CREDIT_MEAN,DAYS_CREDIT_MAX,DAYS_CREDIT_MIN,AMT_CREDIT_SUM_MEAN,AMT_CREDIT_SUM_MAX,AMT_CREDIT_SUM_SUM,AMT_CREDIT_SUM_DEBT_MEAN,AMT_CREDIT_SUM_DEBT_SUM,CREDIT_DAY_OVERDUE_MEAN,CREDIT_DAY_OVERDUE_MAX
0,100001,7,-735.000000,-49,-1572,207623.571429,378000.0,1453365.000,85240.928571,596686.5,0.0,0
1,100002,8,-874.000000,-103,-1437,108131.945625,450000.0,865055.565,49156.200000,245781.0,0.0,0
2,100003,4,-1400.750000,-606,-2586,254350.125000,810000.0,1017400.500,0.000000,0.0,0.0,0
3,100004,2,-867.000000,-408,-1326,94518.900000,94537.8,189037.800,0.000000,0.0,0.0,0
4,100005,3,-190.666667,-62,-373,219042.000000,568800.0,657126.000,189469.500000,568408.5,0.0,0